{% set name = "t2s-fingeruebung" %}
{% set version = "0.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_rev: v0.1.0
  git_url: https://github.com/wr0mb3l/t2s-fingeruebung.git

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - click

about:
  home:
  license: MIT
  license_family: MIT
  summary: Text2Scene Fingeruebung WiSe 2021-22 von Arne Gideon
